package prontopop

import com.raquo.laminar.api.L.*

object Styles:
  /** The one <style> element of the app, built by Laminar and mounted by the landing page.
    *
    * The palette and the five theme variable-sets below are VENDORED from genscalator's design
    * language (a subset: prontopop uses no prose, chip or syntax-token rules). Upstream is
    * GENERATED by DesignLang.scala, so re-sync by copying from there rather than editing tokens
    * here: genscalator/media/design-language/design.css
    * live at https://bjornregnell.se/genscalator/design-language/index.html
    * Vendored 2026-07-25. */
  def createPageStyle: HtmlElement = styleTag(css)

  /** Relative, so the app carries its own fonts and stays deployable on any static host. */
  private val fonts = "fonts"

  private val css = s"""
@font-face { font-family: "Fira Code"; src: url("$fonts/FiraCode-Regular.woff2") format("woff2");
  font-weight: 400; font-style: normal; font-display: swap; }
@font-face { font-family: "Fira Sans"; src: url("$fonts/FiraSans-Regular.woff2") format("woff2");
  font-weight: 400; font-style: normal; font-display: swap; }
@font-face { font-family: "Fira Sans"; src: url("$fonts/FiraSans-Medium.woff2") format("woff2");
  font-weight: 500; font-style: normal; font-display: swap; }
@font-face { font-family: "Fira Sans"; src: url("$fonts/FiraSans-SemiBold.woff2") format("woff2");
  font-weight: 600; font-style: normal; font-display: swap; }

/* the forge palette: fixed tokens, never theme-dependent */
:root {
  --hot-iron-orange: #ee582b;
  --vivid-red-orange: #E22200;
  --chio-light-blue: #11a7d4;
  --cvro-bright-blue: #05b9e9;
  --temper-blue: #095c75;
  --tempered-iron-purple: #17193f;
  --ctip-bone-white: #e8e6c0;
  --anvil-coal-graphite: #322b25;
  --cacg-cold-gray: #cdd4da;
  --coal-ash: #7d6e5f;
  --neon-pink-purple: #c724b1;
  --vivid-bright-green: #38db4e;
  --dark-night-graphite: #14161a;
  --day-light-white: #fafafa;
  --mono: "Fira Code", "Fira Mono", ui-monospace, monospace;
}

/* Automatic (no data-theme): Calm light */
:root {
  --bg: var(--day-light-white);
  --fg: var(--dark-night-graphite);
  --head: var(--dark-night-graphite);
  --link: var(--temper-blue);
  --link-hover: var(--tempered-iron-purple);
  --muted: var(--coal-ash);
  --bg-soft: var(--cacg-cold-gray);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--cacg-cold-gray);
  --rule: var(--coal-ash);
  color-scheme: light;
}

/* Automatic + OS dark: Calm dark */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
    --bg: var(--dark-night-graphite);
    --fg: var(--day-light-white);
    --head: var(--day-light-white);
    --link: var(--chio-light-blue);
    --link-hover: var(--cvro-bright-blue);
    --muted: var(--cacg-cold-gray);
    --bg-soft: var(--tempered-iron-purple);
    --code-bg: var(--tempered-iron-purple);
    --code-fg: var(--ctip-bone-white);
    --border: var(--coal-ash);
    --rule: var(--coal-ash);
    color-scheme: dark;
  }
}

/* Smither light: tempered purple on bone white, headings over a hot-iron rule */
:root[data-theme="smither-light"] {
  --bg: var(--ctip-bone-white);
  --fg: var(--tempered-iron-purple);
  --head: var(--tempered-iron-purple);
  --link: var(--temper-blue);
  --link-hover: var(--tempered-iron-purple);
  --muted: var(--coal-ash);
  --bg-soft: var(--cacg-cold-gray);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--anvil-coal-graphite);
  --rule: var(--hot-iron-orange);
  color-scheme: light;
}

/* Forgy dark: heading and its line must differ, so a hot-iron heading sits over a quiet temper-blue seam */
:root[data-theme="forgy-dark"] {
  --bg: var(--tempered-iron-purple);
  --fg: var(--ctip-bone-white);
  --head: var(--hot-iron-orange);
  --link: var(--cvro-bright-blue);
  --link-hover: var(--chio-light-blue);
  --muted: var(--cacg-cold-gray);
  --bg-soft: var(--anvil-coal-graphite);
  --code-bg: var(--anvil-coal-graphite);
  --code-fg: var(--ctip-bone-white);
  --border: var(--cacg-cold-gray);
  --rule: var(--temper-blue);
  color-scheme: dark;
}

:root[data-theme="calm-dark"] {
  --bg: var(--dark-night-graphite);
  --fg: var(--day-light-white);
  --head: var(--day-light-white);
  --link: var(--chio-light-blue);
  --link-hover: var(--cvro-bright-blue);
  --muted: var(--cacg-cold-gray);
  --bg-soft: var(--tempered-iron-purple);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--coal-ash);
  --rule: var(--coal-ash);
  color-scheme: dark;
}

:root[data-theme="calm-light"] {
  --bg: var(--day-light-white);
  --fg: var(--dark-night-graphite);
  --head: var(--dark-night-graphite);
  --link: var(--temper-blue);
  --link-hover: var(--tempered-iron-purple);
  --muted: var(--coal-ash);
  --bg-soft: var(--cacg-cold-gray);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--cacg-cold-gray);
  --rule: var(--coal-ash);
  color-scheme: light;
}

/* The theme dropdown. The design language pins it to the top right corner; here it sits beside the
   title instead, because on a wide screen a fixed corner puts it far from everything else and out
   of the eye's path — next to the version it is simply found. */
#theme-select {
  margin-left: 3ch;
  font-family: var(--mono); font-size: .8rem; font-weight: bold;
  padding: .3rem .7rem; border-radius: 4px;
  border: 1px solid var(--border); background: var(--code-bg); color: var(--code-fg);
  cursor: pointer;
}

/* prontopop's own surface, spoken in the semantic tokens above */

/* NOT from the design language, so do not expect to find it upstream: the forge palette stops at
   hot-iron orange, around working heat, and yellow is the next step up the same temperature scale
   — welding heat. Added here for the signature chips. */
:root { --welding-yellow: #f5c518; }

* { box-sizing: border-box; }

/* No max-width and no centering: the song table has a FIXED width in characters, so a narrow
   window scrolls sideways instead of reflowing. The background still covers the whole canvas
   because a body background propagates there. */
body {
  font-family: var(--mono);
  font-variant-ligatures: none;
  font-feature-settings: "liga" 0, "calt" 0;
  background: var(--bg);
  color: var(--fg);
  margin: 1rem;
  padding: 0 0 3rem;
  width: max-content;
  min-width: calc(100% - 2rem);
}

/* The seam sits on the title ROW, not on the h1, so it still spans the full width now that the
   theme dropdown shares the line. */
.titlerow {
  align-items: baseline;
  margin: 0.2em 0 0.8em;
  padding-bottom: 0.2em;
  border-bottom: 4px solid var(--rule);
}

h1 {
  color: var(--head);
  font-size: 1.6rem;
  margin: 0;
}

h2 { color: var(--head); font-size: 1.2rem; margin: 0.5rem 0; }

input, select, button {
  font-family: inherit;
  font-size: inherit;
  font-variant-ligatures: none;
  font-feature-settings: "liga" 0, "calt" 0, "dlig" 0;
}

input:not([type="range"]), select {
  background: var(--bg);
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 0.3rem;
  padding: 0.25rem 0.4rem;
}

input:focus, select:focus, button:focus-visible {
  outline: 2px solid var(--link);
  outline-offset: 1px;
}

input.pattern { letter-spacing: 0.2ch; }

/* The signature at a glance: 4/4 in welding yellow, every other signature in light blue. Coloured
   as CHIPS, the way the design language marks state, rather than as text: light blue as text fails
   contrast on the light grounds (2.80 on white, 2.20 on bone), while a chip carries its own pairing
   into all five themes. */
.songrow input.sign {
  background: var(--chio-light-blue);
  color: var(--tempered-iron-purple);
  border-color: var(--chio-light-blue);
  font-weight: bold;
  text-align: center;
}

.songrow input.sign.common {
  background: var(--welding-yellow);
  border-color: var(--welding-yellow);
}

/* The concert name and the saved-concerts dropdown, pinned to the same width so the two rows line
   up. Without this the select sizes itself to its longest option, so it drifted as concerts were
   saved with longer names. */
.concertfield { width: 30ch; }

input[type="range"] { accent-color: var(--hot-iron-orange); }

button {
  padding: 0.3rem 0.8rem;
  border-radius: 0.5rem;
  border: 1px solid var(--border);
  background: var(--bg-soft);
  color: var(--fg);
  cursor: pointer;
}

button:hover { border-color: var(--link); }

/* the playing song, in the signal green the design language gives a healthy state */
.playing, .playing:hover {
  background: var(--vivid-bright-green);
  color: var(--tempered-iron-purple);
  border-color: var(--vivid-bright-green);
}

/* the panic button, in the alert red-orange; white text keeps it AA at button size */
.silence, .silence:hover {
  background: var(--vivid-red-orange);
  color: #ffffff;
  border-color: var(--vivid-red-orange);
}

.silence { font-weight: bold; padding: 0.4rem 1.1rem; margin-right: 2ch; }

/* how many bars Play next and the row buttons run for */
select.bars { margin-right: 2ch; }

.fullscreen { margin-right: 2ch; }

/* starts the song after the cue, in the same signal green a playing song wears */
.playnext, .playnext:hover {
  background: var(--vivid-bright-green);
  color: var(--tempered-iron-purple);
  border-color: var(--vivid-bright-green);
  font-weight: bold;
  padding: 0.4rem 1.1rem;
  margin-right: 2ch;
}

.row { display: flex; flex-wrap: wrap; gap: 0.5ch; align-items: center; margin: 0.5rem 0; }
.row h2 { margin: 0.5rem 0; }

/* The song table: fixed character widths, so a row NEVER reflows — one song, one line, and the
   Play buttons line up in a column down the left. Total width is the sum plus the five gaps. */
/* Column widths live in variables so a loaded concert can size Title and Pattern to its own
   longest entries — see fitWidths in View.scala, which overrides the two elastic ones. The
   defaults here are what an unmeasured table falls back to. Remember a pattern character occupies
   1.2ch, since the field letter-spaces the beats apart; forgetting that once clipped a 4/4
   pattern's closing ':||'. */
:root {
  --col-cue: 3ch;  /* one character: the "@" heading and the ">" marker */
  --col-play: 6ch;  /* "Play" and "Stop" are four characters; the buttons drop their side padding */
  --col-title: 40ch;
  --col-bpm: 6ch;
  --col-sign: 7ch;
  --col-pattern: 38ch;
  --col-remove: 7ch;  /* "Remove" is six characters, and the button has no side padding left */
  --col-gaps: 3ch;  /* the six 0.5ch gaps between seven columns */
}

.songrow {
  display: grid;
  gap: 0.5ch;
  align-items: center;
  margin: 0.25rem 0;
  grid-template-columns:
    var(--col-cue) var(--col-play) var(--col-title) var(--col-bpm)
    var(--col-sign) var(--col-pattern) var(--col-remove);
  width: calc(var(--col-cue) + var(--col-play) + var(--col-title) + var(--col-bpm) +
              var(--col-sign) + var(--col-pattern) + var(--col-remove) + var(--col-gaps));
}

.songrow input { width: 100%; min-width: 0; }

/* the row buttons keep only their vertical padding: each fills its grid column anyway, so the side
   padding bought nothing but width, and the table has to fit a phone held sideways */
.songrow button { padding: 0.3rem 0; }
.songrow.header { color: var(--muted); }
/* the "@" sits over the marker below it */
.songrow.header span:first-child { text-align: center; }

/* the cue column: a ">" at the current or last played song, and on every row a button that moves
   the cue there. It wears the ordinary button look, so the column reads as pressable at a glance
   rather than having to be discovered. */
.songrow button.cue {
  text-align: center;
  color: var(--head);
  font-weight: bold;
}

/* the cued row, outlined so the marked one is clear across a lit stage */
.songrow button.cue.cued { border-color: var(--head); }


.status { margin-top: 1rem; min-height: 1.5em; color: var(--muted); }

/* the keyboard shortcuts, rendered from the same list the key handler reads */
.shortcuts { margin-top: 2rem; }
.shortcuts h2 { margin-bottom: 0.4rem; }
.shortcuts table { border-collapse: collapse; }
.shortcuts th, .shortcuts td { border: 1px solid var(--border); padding: 0.25rem 0.9rem; text-align: left; }
.shortcuts th { background: var(--bg-soft); color: var(--muted); }
.shortcuts td:first-child { font-weight: bold; color: var(--head); white-space: nowrap; }
.shortcuts td:last-child { text-align: center; color: var(--muted); }

/* what is playing, beside the Songs heading */
.nowplaying { margin-left: 2ch; color: var(--muted); }
"""
