package prontopop

import com.raquo.laminar.api.L.*

object Styles:
  /** The one <style> element of the app, built by Laminar and mounted by the landing page.
    *
    * The palette and the five theme variable-sets below are VENDORED from genscalator's design
    * language (a subset: prontopop uses no prose, chip or syntax-token rules). Upstream is
    * GENERATED by DesignLang.scala, so re-sync by copying from there rather than editing tokens
    * here: genscalator/media/design-language/design.css
    * live at https://bjornregnell.se/genscalator/design-language/index.html
    * Vendored 2026-07-25. */
  def createPageStyle: HtmlElement = styleTag(css)

  /** Relative, so the app carries its own fonts and stays deployable on any static host. */
  private val fonts = "fonts"

  private val css = s"""
@font-face { font-family: "Fira Code"; src: url("$fonts/FiraCode-Regular.woff2") format("woff2");
  font-weight: 400; font-style: normal; font-display: swap; }
@font-face { font-family: "Fira Sans"; src: url("$fonts/FiraSans-Regular.woff2") format("woff2");
  font-weight: 400; font-style: normal; font-display: swap; }
@font-face { font-family: "Fira Sans"; src: url("$fonts/FiraSans-Medium.woff2") format("woff2");
  font-weight: 500; font-style: normal; font-display: swap; }
@font-face { font-family: "Fira Sans"; src: url("$fonts/FiraSans-SemiBold.woff2") format("woff2");
  font-weight: 600; font-style: normal; font-display: swap; }

/* the forge palette: fixed tokens, never theme-dependent */
:root {
  --hot-iron-orange: #ee582b;
  --vivid-red-orange: #E22200;
  --chio-light-blue: #11a7d4;
  --cvro-bright-blue: #05b9e9;
  --temper-blue: #095c75;
  --tempered-iron-purple: #17193f;
  --ctip-bone-white: #e8e6c0;
  --anvil-coal-graphite: #322b25;
  --cacg-cold-gray: #cdd4da;
  --coal-ash: #7d6e5f;
  --neon-pink-purple: #c724b1;
  --vivid-bright-green: #38db4e;
  --dark-night-graphite: #14161a;
  --day-light-white: #fafafa;
  --mono: "Fira Code", "Fira Mono", ui-monospace, monospace;
}

/* Automatic (no data-theme): Calm light */
:root {
  --bg: var(--day-light-white);
  --fg: var(--dark-night-graphite);
  --head: var(--dark-night-graphite);
  --link: var(--temper-blue);
  --link-hover: var(--tempered-iron-purple);
  --muted: var(--coal-ash);
  --bg-soft: var(--cacg-cold-gray);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--cacg-cold-gray);
  --rule: var(--coal-ash);
  color-scheme: light;
}

/* Automatic + OS dark: Calm dark */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
    --bg: var(--dark-night-graphite);
    --fg: var(--day-light-white);
    --head: var(--day-light-white);
    --link: var(--chio-light-blue);
    --link-hover: var(--cvro-bright-blue);
    --muted: var(--cacg-cold-gray);
    --bg-soft: var(--tempered-iron-purple);
    --code-bg: var(--tempered-iron-purple);
    --code-fg: var(--ctip-bone-white);
    --border: var(--coal-ash);
    --rule: var(--coal-ash);
    color-scheme: dark;
  }
}

/* Smither light: tempered purple on bone white, headings over a hot-iron rule */
:root[data-theme="smither-light"] {
  --bg: var(--ctip-bone-white);
  --fg: var(--tempered-iron-purple);
  --head: var(--tempered-iron-purple);
  --link: var(--temper-blue);
  --link-hover: var(--tempered-iron-purple);
  --muted: var(--coal-ash);
  --bg-soft: var(--cacg-cold-gray);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--anvil-coal-graphite);
  --rule: var(--hot-iron-orange);
  color-scheme: light;
}

/* Forgy dark: heading and its line must differ, so a hot-iron heading sits over a quiet temper-blue seam */
:root[data-theme="forgy-dark"] {
  --bg: var(--tempered-iron-purple);
  --fg: var(--ctip-bone-white);
  --head: var(--hot-iron-orange);
  --link: var(--cvro-bright-blue);
  --link-hover: var(--chio-light-blue);
  --muted: var(--cacg-cold-gray);
  --bg-soft: var(--anvil-coal-graphite);
  --code-bg: var(--anvil-coal-graphite);
  --code-fg: var(--ctip-bone-white);
  --border: var(--cacg-cold-gray);
  --rule: var(--temper-blue);
  color-scheme: dark;
}

:root[data-theme="calm-dark"] {
  --bg: var(--dark-night-graphite);
  --fg: var(--day-light-white);
  --head: var(--day-light-white);
  --link: var(--chio-light-blue);
  --link-hover: var(--cvro-bright-blue);
  --muted: var(--cacg-cold-gray);
  --bg-soft: var(--tempered-iron-purple);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--coal-ash);
  --rule: var(--coal-ash);
  color-scheme: dark;
}

:root[data-theme="calm-light"] {
  --bg: var(--day-light-white);
  --fg: var(--dark-night-graphite);
  --head: var(--dark-night-graphite);
  --link: var(--temper-blue);
  --link-hover: var(--tempered-iron-purple);
  --muted: var(--coal-ash);
  --bg-soft: var(--cacg-cold-gray);
  --code-bg: var(--tempered-iron-purple);
  --code-fg: var(--ctip-bone-white);
  --border: var(--cacg-cold-gray);
  --rule: var(--coal-ash);
  color-scheme: light;
}

/* The theme dropdown. The design language pins it to the top right corner; here it sits beside the
   title instead, because on a wide screen a fixed corner puts it far from everything else and out
   of the eye's path — next to the version it is simply found. */
#theme-select {
  margin-left: 3ch;
  font-family: var(--mono); font-size: .8rem; font-weight: bold;
  padding: .3rem .7rem; border-radius: 4px;
  border: 1px solid var(--border); background: var(--code-bg); color: var(--code-fg);
  cursor: pointer;
}

/* prontopop's own surface, spoken in the semantic tokens above */

/* NOT from the design language, so do not expect to find it upstream: the forge palette stops at
   hot-iron orange, around working heat, and yellow is the next step up the same temperature scale
   — welding heat. Added here for the signature chips. */
:root { --welding-yellow: #f5c518; }

* { box-sizing: border-box; }

/* No max-width and no centering: the song table has a FIXED width in characters, so a narrow
   window scrolls sideways instead of reflowing. The background still covers the whole canvas
   because a body background propagates there. */
body {
  font-family: var(--mono);
  font-variant-ligatures: none;
  font-feature-settings: "liga" 0, "calt" 0;
  background: var(--bg);
  color: var(--fg);
  margin: 1rem;
  padding: 0 0 3rem;
  width: max-content;
  min-width: calc(100% - 2rem);
}

/* The seam sits on the title ROW, not on the h1, so it still spans the full width now that the
   theme dropdown shares the line. */
.titlerow {
  align-items: baseline;
  margin: 0 0 0.4em;
  padding-bottom: 0.2em;
  border-bottom: 4px solid var(--rule);
}

/* The title reads at the size of everything else: it is a name, not something to be read from the
   back of a room, and the height it was taking belonged to the songs. Bold and in the heading
   colour still tell it apart. */
h1 {
  color: var(--head);
  font-size: 1rem;
  margin: 0;
}

h2 { color: var(--head); font-size: 1.2rem; margin: 0.5rem 0; }

input, select, button {
  font-family: inherit;
  font-size: inherit;
  font-variant-ligatures: none;
  font-feature-settings: "liga" 0, "calt" 0, "dlig" 0;
}

input:not([type="range"]), select {
  background: var(--bg);
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 0.3rem;
  padding: 0.25rem 0.4rem;
}

input:focus, select:focus, button:focus-visible {
  outline: 2px solid var(--link);
  outline-offset: 1px;
}

input.pattern { letter-spacing: 0.2ch; }

/* The signature at a glance: 4/4 in welding yellow, every other signature in light blue. Coloured
   as CHIPS, the way the design language marks state, rather than as text: light blue as text fails
   contrast on the light grounds (2.80 on white, 2.20 on bone), while a chip carries its own pairing
   into all five themes. */
/* the two numeric fields give up what side padding the row's fields still had: they are centred,
   three characters wide, and every character of the column is spoken for */
.songrow input.bpm, .songrow input.sign { padding-left: 0; padding-right: 0; }
.songrow input.bpm { text-align: center; }

.songrow input.sign {
  background: var(--chio-light-blue);
  color: var(--tempered-iron-purple);
  border-color: var(--chio-light-blue);
  font-weight: bold;
  text-align: center;
}

.songrow input.sign.common {
  background: var(--welding-yellow);
  border-color: var(--welding-yellow);
}

/* The concert name and the concert dropdown, pinned to one width. Without this the select sizes
   itself to its longest option, so it drifted as concerts were saved under longer names, and the
   two now share a line where drifting would push the dropdown off a phone. Wide enough for
   "Soaree01 (built-in)" and the select's own arrow. */
.concertfield { width: 23ch; }

/* The name being typed needs far less room than the dropdown, which has to hold the longest title
   anyone has saved plus "(built-in)" and the select's arrow. Ten characters holds a name like
   "Soaree01"; a longer one scrolls inside the field while it is typed. */
input.concertfield { width: 10ch; }

input[type="range"] { accent-color: var(--hot-iron-orange); }

button {
  padding: 0.3rem 0.8rem;
  border-radius: 0.5rem;
  border: 1px solid var(--border);
  background: var(--bg-soft);
  color: var(--fg);
  cursor: pointer;
}

button:hover { border-color: var(--link); }

/* The playing song's own button, in the same alert red-orange the transport wears while it offers
   to stop: both say "Stop" and both do, so one word must not come in two colours. */
.playing, .playing:hover {
  background: var(--vivid-red-orange);
  color: #ffffff;
  border-color: var(--vivid-red-orange);
}

/* The one transport button: the signal green the design language gives a healthy state while it
   offers to play, the alert red-orange while it offers to stop. It is the same button either way,
   so the colour is what says which, and it has to be readable across a room. */
.transport, .transport:hover {
  background: var(--vivid-bright-green);
  color: var(--tempered-iron-purple);
  border-color: var(--vivid-bright-green);
}

/* white text keeps the red AA at button size */
.transport.stopping, .transport.stopping:hover {
  background: var(--vivid-red-orange);
  color: #ffffff;
  border-color: var(--vivid-red-orange);
}

.transport { font-weight: bold; padding: 0.4rem 1.1rem; }

/* The two cue steps only walk the cue, so they stay in the ordinary button colours: nothing sounds
   when they are pressed, and green would promise that it did. An arrow needs less width than a
   word, which is the point of it being one. */
.step { padding: 0.4rem 0.9ch; }

/* how many bars a song runs for: two digits and the select's own arrow, nothing more */
select.bars { width: 6ch; padding-left: 0.3ch; padding-right: 0; margin-right: 2ch; }

.row { display: flex; flex-wrap: wrap; gap: 0.5ch; align-items: center; margin: 0.5rem 0; }
.row h2 { margin: 0.5rem 0; }

/* The song table: fixed character widths, so a row NEVER reflows — one song, one line, and the
   Play buttons line up in a column down the left. Total width is the sum plus the five gaps. */
/* Column widths live in variables so a loaded concert can size Title and Pattern to its own
   longest entries — see fitWidths in View.scala, which overrides the two elastic ones. The
   defaults here are what an unmeasured table falls back to. Remember a pattern character occupies
   1.2ch, since the field letter-spaces the beats apart; forgetting that once clipped a 4/4
   pattern's closing ':||'. */
:root {
  --col-cue: 3ch;  /* one character: the "@" heading and the ">" marker */
  /* The three fixed narrow columns are cut close to their contents: four characters for
     "Play"/"Stop", three for a tempo or a signature, plus the field's own border and a hair for
     the caret. There is no side padding left to give. */
  --col-play: 4.6ch;
  --col-title: 40ch;
  --col-bpm: 4.2ch;
  --col-sign: 4.2ch;  /* also the width of the "Sig." above it */
  --col-pattern: 38ch;
  --col-remove: 7ch;  /* "Remove" is six characters, and the button has no side padding left */
  --col-gap: 0.25ch;  /* between two columns; the fields' own borders do most of the separating */
  --col-gaps: calc(var(--col-gap) * 6);  /* the six gaps between seven columns */
}

.songrow {
  display: grid;
  gap: var(--col-gap);
  align-items: center;
  /* the fields are boxes with their own borders, so a hair between rows is enough to keep two of
     them apart; a taller gap only pushed songs off the bottom of a phone */
  margin: 0.1rem 0;
  grid-template-columns:
    var(--col-cue) var(--col-play) var(--col-bpm) var(--col-sign)
    var(--col-title) var(--col-pattern) var(--col-remove);
  width: calc(var(--col-cue) + var(--col-play) + var(--col-title) + var(--col-bpm) +
              var(--col-sign) + var(--col-pattern) + var(--col-remove) + var(--col-gaps));
}

/* The row's fields keep their vertical padding but hand back most of the sides: it was the padding
   that set how narrow each column could be drawn, and the table has to fit a phone held sideways.
   fitWidths in View.scala allows for what is left. */
.songrow input { width: 100%; min-width: 0; padding-left: 0.2rem; padding-right: 0.2rem; }

/* the row buttons keep only their vertical padding: each fills its grid column anyway, so the side
   padding bought nothing but width, and the table has to fit a phone held sideways */
.songrow button { padding: 0.3rem 0; }
.songrow.header { color: var(--muted); }
/* the "@" sits over the marker below it */
.songrow.header span:first-child { text-align: center; }

/* the cue column: a ">" at the current or last played song, and on every row a button that moves
   the cue there. It wears the ordinary button look, so the column reads as pressable at a glance
   rather than having to be discovered. */
.songrow button.cue {
  text-align: center;
  color: var(--head);
  font-weight: bold;
}

/* the cued row, outlined so the marked one is clear across a lit stage */
.songrow button.cue.cued { border-color: var(--head); }


/* No reserved height: it stood empty most of the time, holding a line and a half of screen against
   a message that may never come. The page shifts by one line when a message does arrive, which is
   the trade — and a message means something worth being shifted by. */
.status { margin-top: 0.5rem; color: var(--muted); }

/* The keyboard shortcuts, rendered from the same list the key handler reads. A reference to glance
   at, not a section to be announced: its heading is the size of the text under it, and the rows are
   as close as they can be and stay legible. */
.shortcuts { margin-top: 1rem; }
.shortcuts h2 { font-size: 1rem; margin: 0 0 0.2rem; }
.shortcuts table { border-collapse: collapse; }
.shortcuts th, .shortcuts td { border: 1px solid var(--border); padding: 0.1rem 0.9rem; text-align: left; }
.shortcuts th { background: var(--bg-soft); color: var(--muted); }
.shortcuts td:first-child { font-weight: bold; color: var(--head); white-space: nowrap; }
.shortcuts td:last-child { text-align: center; color: var(--muted); }

/* what is playing, riding along at the end of the controls */
.nowplaying { margin-left: 2ch; color: var(--muted); }

/* Save says whether there is anything to save: warm orange while the table holds something the
   Local Store does not, the ordinary button otherwise. Orange rather than the alert red-orange
   deliberately — red is kept for the two things that matter on a stage, a song sounding and work
   about to be lost, and a third red would dilute both. */
.save.dirty, .save.dirty:hover {
  background: var(--hot-iron-orange);
  color: var(--tempered-iron-purple);
  border-color: var(--hot-iron-orange);
  font-weight: bold;
}

/* room between saving a concert, choosing one, and adding to one, since they share a line */
.loadlabel { margin-left: 2ch; }
.addsong { margin-left: 2ch; }
.removeconcert { margin-left: 1ch; }

/* A disabled button says "not for this concert", not "broken": dimmed, and it stops looking
   pressable. Removing a built-in is the one thing this row cannot do. */
button:disabled, button:disabled:hover {
  opacity: 0.45;
  cursor: default;
  border-color: var(--border);
}

/* The question before a load discards edits. Fixed to the viewport rather than the page, which is
   as wide as the song table and scrolls sideways under it. */
.backdrop {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
}

.dialog {
  background: var(--bg);
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 0.6rem;
  padding: 1rem 1.4rem 1.2rem;
  max-width: 52ch;
  box-shadow: 0 0.5rem 2rem rgba(0, 0, 0, 0.5);
}

.dialog h2 { margin-top: 0; }
.dialog p { line-height: 1.5; }
.dialog .concertname { color: var(--head); font-weight: bold; }
.dialog .row { margin-bottom: 0; }
.dialog button { padding: 0.4rem 1.1rem; }

/* Cancel is the safe answer and takes the focus, so it is the one that looks pressed-by-default;
   the destructive one wears the alert red-orange and has to be aimed at. */
.cancel { font-weight: bold; margin-right: 2ch; }

.discard, .discard:hover {
  background: var(--vivid-red-orange);
  color: #ffffff;
  border-color: var(--vivid-red-orange);
}
"""
